# Generated by Django 4.2.8 on 2023-12-13 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("admin_id", models.CharField(max_length=10, unique=True)),
                ("admin_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Counselor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_id", models.CharField(max_length=10)),
                ("major", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("contact_number", models.CharField(max_length=15)),
                ("introduction", models.TextField()),
                ("major", models.CharField(max_length=50)),
                ("class_name", models.CharField(max_length=20)),
                ("student_id", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_number", models.CharField(max_length=10, unique=True)),
                ("is_approved", models.BooleanField(default=False)),
                ("job_title", models.CharField(max_length=100)),
                ("job_content", models.TextField()),
                ("salary", models.IntegerField()),
                ("feedback", models.TextField(blank=True, null=True)),
                ("student_job_fk", models.ManyToManyField(to="campusapp.student")),
            ],
        ),
        migrations.CreateModel(
            name="Employer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employer_id", models.CharField(max_length=10, unique=True)),
                ("employer_name", models.CharField(max_length=100)),
                ("contact_number", models.CharField(max_length=15)),
                ("jobs_em_fk_2", models.ManyToManyField(to="campusapp.job")),
            ],
        ),
    ]
