# Generated by Django 4.2.8 on 2023-12-13 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campusapp", "0002_login_studentaffairs_workstudyadmin_delete_admin_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="StudentAffairs",
            new_name="StudentAffair",
        ),
        migrations.RenameField(
            model_name="studentaffair",
            old_name="stuadmin_name",
            new_name="stu_admin_name",
        ),
    ]
