# Generated by Django 4.2.8 on 2023-12-13 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campusapp", "0003_rename_studentaffairs_studentaffair_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="login",
            old_name="user_names",
            new_name="user_name",
        ),
        migrations.RenameField(
            model_name="login",
            old_name="user_passwords",
            new_name="user_password",
        ),
    ]
