# Generated by Django 4.2.8 on 2023-12-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campusapp", "0004_rename_user_names_login_user_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="contact_number",
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
