# Generated by Django 4.2.8 on 2023-12-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campusapp", "0005_alter_student_contact_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="login",
            name="user_id",
            field=models.CharField(default="0000", max_length=10),
        ),
    ]
