# Generated by Django 4.2.8 on 2023-12-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campusapp", "0006_login_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="login",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("Student", "Student"),
                    ("Counselor", "Counselor"),
                    ("Employer", "Employer"),
                    ("Work Study Admin", "Work Study Admin"),
                    ("Student Affairs", "Student Affairs"),
                ],
                max_length=20,
            ),
        ),
    ]
