@startuml  
skin rose
actor 企业 #Red/Blue
boundary "：企业管理界面" #Red/Blue
boundary "：岗位信息弹窗" #Red/Blue
control "：数据访问层" #Red/Blue
entity "：岗位信息" #Red/Blue
skinparam sequenceParticipant underline
hide footbox


opt 添加岗位信息
企业 -> "：企业管理界面" : 输入企业信息
activate 企业
activate "：企业管理界面"
alt 合法企业信息
"：企业管理界面" -> "：数据访问层" : 提交职位
activate "：数据访问层"
"：数据访问层" -> "：岗位信息" : 根据职位名查找岗位信息
activate "：岗位信息"
else 不合法岗位信息
"：企业管理界面" --> "企业" : 提示添加失败
end
"：岗位信息" --> "：数据访问层" : 返回布尔值flag
deactivate "：岗位信息"
"：数据访问层" --> "：企业管理界面" : 返回布尔值flag
deactivate "：数据访问层"

else 管理企业信息
alt flag = true
"：企业管理界面" --> "企业" : 提示添加失败
else flag = false
"：企业管理界面" -> "：数据访问层" : 提交岗位信息
activate "：数据访问层"
"：数据访问层" -> "：岗位信息" : 添加岗位信息
activate "：岗位信息"
"：岗位信息" --> "：数据访问层" : 返回true
deactivate "：岗位信息"
"：数据访问层" --> "：企业管理界面" : 返回true
deactivate "：数据访问层"
"：企业管理界面" -> "企业" : 提示添加成功
end

企业 -> "：企业管理界面" : 点击管理按钮
"：企业管理界面" -> "：岗位信息弹窗" : 提出显示请求
activate "：岗位信息弹窗"

activate "：数据访问层"
"：岗位信息弹窗" -> "：数据访问层" : 根据工位号请求访问岗位信息

"：数据访问层" -> "：岗位信息" : 根据工位号请求访问岗位信息

activate "：岗位信息"
"：岗位信息" --> "：数据访问层" : 返回岗位信息
deactivate "：岗位信息"

"：数据访问层" --> "：岗位信息弹窗" : 返回岗位信息
deactivate "：数据访问层"
"：岗位信息弹窗" --> "企业" : 显示岗位信息

opt 删除岗位信息

"：岗位信息弹窗" -> "：数据访问层" : 提交工位号
activate "：数据访问层"
"：数据访问层" -> "：岗位信息" : 根据工位号删除岗位信息
activate "：岗位信息"
"：岗位信息" --> "：数据访问层" : 返回true
deactivate "：岗位信息"
"：数据访问层" --> "：岗位信息弹窗" : 返回true
deactivate "：数据访问层"

else 修改岗位信息

"：岗位信息弹窗" -> "：数据访问层" : 提交重新输入后的岗位信息
activate "：数据访问层"
"：数据访问层" -> "：岗位信息" : 根据工位号对岗位信息进行更新
activate "：岗位信息"
"：岗位信息" --> "：数据访问层" : 返回true
deactivate "：岗位信息"
"：数据访问层" --> "：岗位信息弹窗" : 返回true
deactivate "：数据访问层"

else 退出弹窗

"：岗位信息弹窗" --> "：企业管理界面" : 返回
destroy "：岗位信息弹窗"

end

else 提交反馈
企业 -> "：企业管理界面" : 输入反馈信息
"：企业管理界面" -> "：数据访问层" : 提交工位号和反馈信息
activate "：数据访问层"
"：数据访问层" -> "：岗位信息" : 根据工位号提交反馈
activate "：岗位信息"
"：岗位信息" --> "：数据访问层" : 返回true
deactivate "：岗位信息"
"：数据访问层" --> "：企业管理界面" : 返回true
deactivate "：数据访问层"
"：企业管理界面" -> "企业" : 提示提交成功

end
@enduml
