@startuml  
skin rose
actor 用户 #Red/Blue
boundary "：登录界面" #Red/Blue
boundary "：用户界面" #Red/Blue
control "：数据访问层" #Red/Blue
entity "：用户信息" #Red/Blue
entity "：岗位信息" #Red/Blue
skinparam sequenceParticipant underline
hide footbox
par 
用户 -> "：登录界面" : 输入账号
activate "：登录界面"
用户 -> "：登录界面" : 输入密码
end
activate 用户

"：登录界面" -> "：数据访问层" : 提交账号密码
activate "：数据访问层"
"：数据访问层" -> "：用户信息" : 提交账号密码
activate "：用户信息"
"：用户信息" --> "：数据访问层" : 返回标志值flag
deactivate "：用户信息"
"：数据访问层" --> "：登录界面" : 返回标志值flag
deactivate "：数据访问层"
alt flag = -1
"：登录界面" --> "用户" : 显示登录失败

else flag = 1 //学生
"：登录界面" -> "：用户界面" : 登录
deactivate "：登录界面"
activate "：用户界面"
par
"：用户界面" -> "：数据访问层" : 请求访问企业信息
activate "：数据访问层"
"：用户界面" -> "：数据访问层" : 根据学号请求访问学生用户信息
"：数据访问层" -> "：用户信息" : 请求访问企业信息
activate "：用户信息"
"：数据访问层" -> "：用户信息" : 根据学号请求访问学生用户信息
end
par
activate "：用户信息"
"：用户信息" --> "：数据访问层" : 返回学生用户信息
"：用户信息" --> "：数据访问层" : 返回企业信息
deactivate "：用户信息"
end

par
"：数据访问层" --> "：用户界面" : 返回学生用户信息
"：用户界面" --> "用户" : 显示学生用户信息
"：数据访问层" -> "：岗位信息" : 请求岗位信息
end

activate "：岗位信息"
"：岗位信息" -> "：数据访问层" : 返回岗位信息
deactivate "：岗位信息"
"：数据访问层" --> "：用户界面" : 返回岗位信息
deactivate "：数据访问层"
"：用户界面" --> "用户" : 显示岗位信息



else flag = 2 //学生处
"：登录界面" -> "：用户界面" : 登录
activate "：登录界面"
deactivate "：登录界面"
activate "：数据访问层"
"：用户界面" -> "：数据访问层" : 根据教工号请求访问学生处用户信息
"：数据访问层" -> "：用户信息" : 请求访问学生处用户信息
activate "：用户信息"
"：用户信息" --> "：数据访问层" : 返回学生处用户信息
deactivate "：用户信息"
"：数据访问层" -> "：岗位信息" : 请求访问岗位信息
activate "：岗位信息"
"：岗位信息" --> "：数据访问层" : 返回岗位信息
deactivate "：岗位信息"
"：数据访问层" --> "：用户界面" : 返回数据
deactivate "：数据访问层"
"：用户界面" --> "用户" : 显示数据

else flag = 3 // 企业单位

"：登录界面" -> "：用户界面" : 登录
activate "：登录界面"
deactivate "：登录界面"
activate "：数据访问层"
"：用户界面" -> "：数据访问层" : 根据企业名请求访问企业用户信息
"：数据访问层" -> "：用户信息" : 请求访问企业用户信息
activate "：用户信息"
"：用户信息" --> "：数据访问层" : 返回企业用户信息
deactivate "：用户信息"
"：数据访问层" -> "：岗位信息" : 请求访问岗位信息
activate "：岗位信息"
"：岗位信息" --> "：数据访问层" : 返回岗位信息
deactivate "：岗位信息"
"：数据访问层" -> "：用户信息" : 请求访问学生用户信息
activate "：用户信息"
"：用户信息" --> "：数据访问层" : 返回学生用户信息
deactivate "：用户信息"
"：数据访问层" --> "：用户界面": 返回数据
"：用户界面" --> "用户": 显示数据
deactivate "：数据访问层"

else flag = 4 // 勤工处

"：登录界面" -> "：用户界面" : 登录
activate "：登录界面"
deactivate "：登录界面"
activate "：数据访问层"
"：用户界面" -> "：数据访问层" : 根据工号请求访问勤工用户信息
"：数据访问层" -> "：用户信息" : 请求访问勤工用户信息
activate "：用户信息"
"：用户信息" --> "：数据访问层" : 返回勤工用户信息
deactivate "：用户信息"
"：数据访问层" -> "：岗位信息" : 请求访问岗位信息
activate "：岗位信息"
"：岗位信息" --> "：数据访问层" : 返回岗位信息
deactivate "：岗位信息"
"：数据访问层" -> "：用户信息" : 根据岗位请求访问学生用户信息
activate "：用户信息"
"：用户信息" --> "：数据访问层" : 返回学生用户信息
deactivate "：用户信息"
"：数据访问层" --> "：用户界面": 返回数据
"：用户界面" --> "用户": 显示数据
deactivate "：数据访问层"

else flag = 5 // 辅导员
"：登录界面" -> "：用户界面" : 登录
activate "：登录界面"
deactivate "：登录界面"
activate "：数据访问层"
"：用户界面" -> "：数据访问层" : 根据教工号请求访问辅导员信息
"：数据访问层" -> "：用户信息" : 请求访问辅导员信息
activate "：用户信息"
"：用户信息" --> "：数据访问层" : 返回辅导员信息
"：数据访问层" -> "：用户信息" : 根据教工号请求访问学生信息
"：用户信息" --> "：数据访问层" : 返回学生信息
"：数据访问层" -> "：岗位信息" : 根据学号请求访问岗位信息
deactivate "：用户信息"
activate "：岗位信息"
"：岗位信息" --> "：数据访问层" : 返回岗位信息
deactivate "：岗位信息"
"：数据访问层" --> "：用户界面" : 返回数据
deactivate "：数据访问层"
"：用户界面" --> "用户" : 显示数据
end
@enduml
