@startuml  
skin rose
actor 学生处 #Red/Blue
boundary "：学生处管理界面" #Red/Blue
boundary "：学生信息弹窗" #Red/Blue
control "：数据访问层" #Red/Blue
entity "：学生信息" #Red/Blue
skinparam sequenceParticipant underline

hide footbox

opt 添加学生信息
学生处 -> "：学生处管理界面" : 输入学生信息
activate 学生处
activate "：学生处管理界面"
alt 合法学生信息
"：学生处管理界面" -> "：数据访问层" : 提交学号
activate "：数据访问层"
"：数据访问层" -> "：学生信息" : 根据学号查找学生信息
activate "：学生信息"
else 不合法学生信息
"：学生处管理界面" --> "学生处" : 提示添加失败
end
"：学生信息" --> "：数据访问层" : 返回布尔值flag
deactivate "：学生信息"
"：数据访问层" --> "：学生处管理界面" : 返回布尔值flag
deactivate "：数据访问层"

else 管理学生信息
alt flag = true
"：学生处管理界面" --> "学生处" : 提示添加失败
else flag = false
"：学生处管理界面" -> "：数据访问层" : 提交学生信息
activate "：数据访问层"
"：数据访问层" -> "：学生信息" : 添加学生信息
activate "：学生信息"
"：学生信息" --> "：数据访问层" : 返回true
deactivate "：学生信息"
"：数据访问层" --> "：学生处管理界面" : 返回true
deactivate "：数据访问层"
"：学生处管理界面" -> "学生处" : 提示添加成功
end

学生处 -> "：学生处管理界面" : 点击管理按钮
"：学生处管理界面" -> "：学生信息弹窗" : 提出显示请求
activate "：学生信息弹窗"

activate "：数据访问层"
"：学生信息弹窗" -> "：数据访问层" : 根据学号请求访问学生用户信息

"：数据访问层" -> "：学生信息" : 根据学号请求访问学生用户信息

activate "：学生信息"
"：学生信息" --> "：数据访问层" : 返回学生用户信息
deactivate "：学生信息"

"：数据访问层" --> "：学生信息弹窗" : 返回学生用户信息
deactivate "：数据访问层"
"：学生信息弹窗" --> "学生处" : 显示学生用户信息

opt 删除学生信息

"：学生信息弹窗" -> "：数据访问层" : 提交学号
activate "：数据访问层"
"：数据访问层" -> "：学生信息" : 根据学号删除学生信息
activate "：学生信息"
"：学生信息" --> "：数据访问层" : 返回true
deactivate "：学生信息"
"：数据访问层" --> "：学生信息弹窗" : 返回true
deactivate "：数据访问层"

else 修改学生信息

"：学生信息弹窗" -> "：数据访问层" : 提交重新输入后的学生信息
activate "：数据访问层"
"：数据访问层" -> "：学生信息" : 根据学号对学生信息进行更新
activate "：学生信息"
"：学生信息" --> "：数据访问层" : 返回true
deactivate "：学生信息"
"：数据访问层" --> "：学生信息弹窗" : 返回true
deactivate "：数据访问层"

else 退出弹窗

"：学生信息弹窗" --> "：学生处管理界面" : 返回
destroy "：学生信息弹窗"

end
end
@enduml  